services:
  - type: web
    name: ems-backend
    runtime: docker
    plan: free
    rootDir: backend
    envVars:
      - key: APP_KEY
        value: base64:Y3d3c3dkd3d3c3d3d3d3d3d3d3d3d3d3d3d3d3d3d3c=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: ems-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
